### ISSUE TITLE
AttributeError: 'captcha' object has no attribute 'logger'

### ISSUE THREAD

**Issue by thijstriemstra** [FSecureLABS/captcha22#10]
```
INFO:Captcha22 Engine:Create model
INFO:Captcha22 Engine:./Unsorted/admin_testcaptcha1_1.zip
INFO:Captcha22 Engine:Updating file
INFO:Captcha22 Engine:Done
INFO:Captcha22 Engine:Going to start the model training procedure
Traceback (most recent call last):
  File "/home/thijs/.virtualenvs/captcha/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/home/thijs/.virtualenvs/captcha/lib/python3.7/site-packages/captcha22/__main__.py", line 404, in main
    args.func(args)
  File "/home/thijs/.virtualenvs/captcha/lib/python3.7/site-packages/captcha22/lib/core/server.py", line 23, in server
    server.main()
  File "/home/thijs/.virtualenvs/captcha/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 517, in main
    self.run_server()
  File "/home/thijs/.virtualenvs/captcha/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 493, in run_server
    self.continue_training()
  File "/home/thijs/.virtualenvs/captcha/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 467, in continue_training
    model.start_training()
  File "/home/thijs/.virtualenvs/captcha/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 201, in start_training
    self.logger.info("Starting training")
AttributeError: 'captcha' object has no attribute 'logger'
```

**Comment by TinusGreen** [comment]
Issue resolved with https://github.com/FSecureLABS/captcha22/commit/4cd99e510ee998d5ddfa128708c928a4d0254c91

Please advise if issue persists
