### ISSUE TITLE
no training process

### ISSUE THREAD

**Issue by xja** [FSecureLABS/captcha22#15]
OS: Ubuntu 20.04.2 LTS in wsl2
Python: Anaconda python 3.7.9
Tensorflow: 1.15.5, cpu only
```
(captcha22) user1@DESKTOP-ABCDEF:~/anaconda3/envs/captcha22$ captcha22 server engine
INFO:Captcha22 Engine:Captcha22 engine start
INFO:Captcha22 Engine:Starting training
INFO:Captcha22 Engine:Checking if there are any new files
INFO:Captcha22 Engine:Start running
INFO:Captcha22 Engine:Model update
INFO:Captcha22 Engine:Testing training level
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/captcha22/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/captcha22/__main__.py", line 278, in main
    args.func(args)
  File "/home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/captcha22/lib/core/server.py", line 22, in server
    server.main()
  File "/home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 519, in main
    self.run_server()
  File "/home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 495, in run_server
    self.continue_training()
  File "/home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 437, in continue_training
    model.test_training_level()
  File "/home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/captcha22/lib/server/captcha22.py", line 138, in test_training_level
    step = ast.literal_eval(values[1].split('Step ')[1].split(':')[0])
IndexError: list index out of range
```
direct aocr execution and output:
```
(captcha22) user1@DESKTOP-ABCDEF:~/anaconda3/envs/captcha22/Busy/admin/test/1$ aocr train --max-height 220 --max-width 50 labels/training.tfrecords
WARNING:tensorflow:From /home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/aocr/__main__.py:20: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /home/user1/anaconda3/envs/captcha22/lib/python3.7/site-packages/aocr/__main__.py:20: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

2021-04-12 18:10:29.129743: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2195015000 Hz
2021-04-12 18:10:29.134487: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55bdab3d0040 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-12 18:10:29.134673: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-12 18:10:29,140 root  INFO     phase: train
2021-04-12 18:10:29,140 root  INFO     model_dir: ./checkpoints
2021-04-12 18:10:29,141 root  INFO     load_model: True
2021-04-12 18:10:29,141 root  INFO     output_dir: ./results
2021-04-12 18:10:29,141 root  INFO     steps_per_checkpoint: 100
2021-04-12 18:10:29,142 root  INFO     batch_size: 65
2021-04-12 18:10:29,142 root  INFO     learning_rate: 1.000000
2021-04-12 18:10:29,142 root  INFO     reg_val: 0
2021-04-12 18:10:29,142 root  INFO     max_gradient_norm: 5.000000
2021-04-12 18:10:29,143 root  INFO     clip_gradients: True
2021-04-12 18:10:29,143 root  INFO     max_image_width 50.000000
2021-04-12 18:10:29,143 root  INFO     max_prediction_length 8.000000
2021-04-12 18:10:29,143 root  INFO     channels: 1
2021-04-12 18:10:29,143 root  INFO     target_embedding_size: 10.000000
2021-04-12 18:10:29,144 root  INFO     attn_num_hidden: 128
2021-04-12 18:10:29,144 root  INFO     attn_num_layers: 2
2021-04-12 18:10:29,144 root  INFO     visualize: False
2021-04-12 18:10:45,579 root  INFO     Reading model parameters from ./checkpoints/model.ckpt-0
2021-04-12 18:10:46.030381: W tensorflow/core/common_runtime/colocation_graph.cc:983] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
Assign: CPU 
RandomUniform: CPU XLA_CPU 
Const: CPU XLA_CPU 
Mul: CPU XLA_CPU 
Sub: CPU XLA_CPU 
ApplyAdadelta: CPU 
Add: CPU XLA_CPU 
Identity: CPU XLA_CPU 
VariableV2: CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  conv_conv1/W/Initializer/random_uniform/shape (Const) 
  conv_conv1/W/Initializer/random_uniform/min (Const) 
  conv_conv1/W/Initializer/random_uniform/max (Const) 
  conv_conv1/W/Initializer/random_uniform/RandomUniform (RandomUniform) 
  conv_conv1/W/Initializer/random_uniform/sub (Sub) 
  conv_conv1/W/Initializer/random_uniform/mul (Mul) 
  conv_conv1/W/Initializer/random_uniform (Add) 
  conv_conv1/W (VariableV2) /device:GPU:0
  conv_conv1/W/Assign (Assign) /device:GPU:0
  conv_conv1/W/read (Identity) /device:GPU:0
  conv_conv1/W/Adadelta/Initializer/zeros (Const) /device:GPU:0
  conv_conv1/W/Adadelta (VariableV2) /device:GPU:0
  conv_conv1/W/Adadelta/Assign (Assign) /device:GPU:0
  conv_conv1/W/Adadelta/read (Identity) /device:GPU:0
  conv_conv1/W/Adadelta_1/Initializer/zeros (Const) /device:GPU:0
  conv_conv1/W/Adadelta_1 (VariableV2) /device:GPU:0
  conv_conv1/W/Adadelta_1/Assign (Assign) /device:GPU:0
  conv_conv1/W/Adadelta_1/read (Identity) /device:GPU:0
  Adadelta/update_conv_conv1/W/ApplyAdadelta (ApplyAdadelta) /device:GPU:0
  save/Assign_13 (Assign) /device:GPU:0
  save/Assign_14 (Assign) /device:GPU:0
  save/Assign_15 (Assign) /device:GPU:0

2021-04-12 18:10:46.032016: W tensorflow/core/common_runtime/colocation_graph.cc:983] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices:
[...] 
2021-04-12 18:10:50.219172: W tensorflow/core/common_runtime/colocation_graph.cc:983] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
Switch: CPU XLA_CPU 
Enter: CPU XLA_CPU 
LookupTableFindV2: CPU 
LookupTableInsertV2: CPU 
MutableHashTableV2: CPU 
LookupTableExportV2: CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  MutableHashTable (MutableHashTableV2) /device:GPU:0
  MutableHashTable_lookup_table_export_values/LookupTableExportV2 (LookupTableExportV2) /device:GPU:0
  MutableHashTable_lookup_table_insert/LookupTableInsertV2 (LookupTableInsertV2) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter_1 (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Switch (Switch) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter_2 (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter_3 (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Switch_2 (Switch) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2 (LookupTableFindV2) /device:GPU:0

2021-04-12 18:10:52,255 root  INFO     Global step 0. Time: 0.000, loss: 0.000000, perplexity: 1.00.
2021-04-12 18:10:52,255 root  INFO     Finishing the training and saving the model at step 0.
``` 
it just repeat the warning message until the end of the execution

**Comment by TinusGreen** [comment]
Hi xja,

That seems to be a Tensorflow issue. It is failing to create the training graph on your CPU. I don't think you have sufficient resources available for graph placement. In these cases, what works best is to then attempt to do a soft placement.

My suggestion would have been to modify AOCR to allow soft placement, however, reviewing their source code I see they already do. See line 215 here: https://github.com/emedvedev/attention-ocr/blob/master/aocr/__main__.py

I do think the only way your would be able to support this would be with the GPU version of Tensorflow. Otherwise, my recommendation would be to log this issue directly with Tensorflow.
