### ISSUE TITLE
No tensorflow.contrib and aocr.log

### ISSUE THREAD

**Issue by GEkuL** [FSecureLABS/captcha22#17]
Hi,
I got problems while training.
1) `ModuleNotFoundError: No module named 'tensorflow.contrib'`
2) `FileNotFoundError: [Errno 2] No such file or directory: './Busy/admin/try1/1/aocr.log'`
 
There  were other errors but they seemed to be about GPU, since I'm using CPU for Tensor. So I didn't includ them.

Could you  help me with the issues?

Here's the log from terminal.
```
Traceback (most recent call last):
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/aocr/model/seq2seq.py", line 73, in <module>
    linear = rnn_cell_impl._linear  # pylint: disable=protected-access
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../Captcha/captcha_env/bin/aocr", line 11, in <module>
    load_entry_point('aocr==0.7.6', 'console_scripts', 'aocr')()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/aocr/__main__.py", line 14, in <module>
    from .model.model import Model
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/aocr/model/model.py", line 18, in <module>
    from .seq2seq_model import Seq2SeqModel
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/aocr/model/seq2seq_model.py", line 25, in <module>
    from .seq2seq import model_with_buckets
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/aocr/model/seq2seq.py", line 76, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
ModuleNotFoundError: No module named 'tensorflow.contrib'
INFO:Captcha22 Engine:Create model
INFO:Captcha22 Engine:./Unsorted/admin_try1_1.zip
INFO:Captcha22 Engine:Updating file
INFO:Captcha22 Engine:Done
INFO:Captcha22 Engine:Going to start the model training procedure
INFO:Captcha22 Engine:Starting training
INFO:Captcha22 Engine:Starting wait cycle
nohup: appending output to 'nohup.out'
INFO:Captcha22 Engine:Model update
INFO:Captcha22 Engine:Testing training level
Traceback (most recent call last):
  File ".../Captcha/captcha_env/bin/captcha22", line 11, in <module>
    load_entry_point('captcha22==1.0.6', 'console_scripts', 'captcha22')()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/captcha22/__main__.py", line 278, in main
    args.func(args)
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/captcha22/lib/core/server.py", line 22, in server
    server.main()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/captcha22/lib/server/captcha22.py", line 519, in main
    self.run_server()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/captcha22/lib/server/captcha22.py", line 495, in run_server
    self.continue_training()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/captcha22/lib/server/captcha22.py", line 437, in continue_training
    model.test_training_level()
  File ".../Captcha/captcha_env/lib/python3.8/site-packages/captcha22/lib/server/captcha22.py", line 130, in test_training_level
    f = open(self.path + "aocr.log")
FileNotFoundError: [Errno 2] No such file or directory: './Busy/admin/try1/1/aocr.log'

```

**Comment by GEkuL** [comment]
[It's said](https://stackoverflow.com/questions/60882663/modulenotfounderror-no-module-named-tensorflow-contrib-with-tensorflow-2-0-0) that from the 2.0 version tf.contrib was deprecated, so there's no such module on the modern versions

I think it's needed to be updated here
```
File ".../Captcha/captcha_env/lib/python3.8/site-packages/aocr/model/seq2seq.py", line 76, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by GEkuL** [comment]
Just tried python3.7 with tensorflow1.15 on  the board. The problem seem to be solved!

I think the **documentation should specify the python and tensorflow versions**.

By the way, it's also a good idea to provide **an example of the name of ZIP**. Because now it's definitely not clear enough.

**Comment by TinusGreen** [comment]
Hi GEkuL,

As indicated in the readme under prerequisites, we currently only support tensorflow versions below 2. Also see #9 and #11. This is due to our use of the [AOCR](https://github.com/emedvedev/attention-ocr) pip package for model training and creation. AOCR does not support tensorflow 2+. The python version does not really matter actually, only the tensorflow version.

We are in the process of migrating our model training to an self-developed tensorflow package, which will eliminate the dependency on AOCR, but this will take quite a bit of time. We will first release the new GUI version, after which we will then start with the migration. 

In terms of the zip names, the idea is that you interface with the server through the API. If you make use of the client API, the naming is done for you. In the GUI version this will also be made easier. If however you decide to execute the standalone server, like mentioned in the readme about the cracking scripts, at that point some level of customisation will be involved.
