### ISSUE TITLE
error: List index out of range (img = cv2.imread(image[0]) when i run captcha2 server engine

### ISSUE THREAD

**Issue by vneroica** [FSecureLABS/captcha22#19]
i installed captcha22 via pip in an Ubuntu Server 18.04 lts, Python 3.6 and Tensorflow 1.15.

I got an error when i run the command "Captcha22 server engine":

INFO:Captcha22 Engine:Captcha22 engine start
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 37, in __init__
    self.hasTrained = ast.literal_eval(lines[0].replace("\n", ""))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/captcha22/__main__.py", line 278, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/core/server.py", line 22, in server
    server.main()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 518, in main
    self.first_start()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 514, in first_start
    self.reload_models(layer + "/")
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 383, in reload_models
    model = captcha(path, self.logger)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 55, in __init__
    self.get_image_size()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 61, in get_image_size
    img = cv2.imread(images[0])
IndexError: list index out of range

Please help me to solve this problem.

**Comment by vneroica** [comment]
full error log when i run the command  "captcha22 server engine" first time:

 extracting: ./Busy/admin/test/01/captcha-solve-vn/captchas/yyn57.png  
INFO:Captcha22 Engine:Create labels
INFO:Captcha22 Engine:Directories is:
INFO:Captcha22 Engine:./Busy/admin/test/01/data/
INFO:Captcha22 Engine:./Busy/admin/test/01/labels/
INFO:Captcha22 Engine:Generate aocr
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

2021-09-05 14:46:14.934520: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-05 14:46:14.944192: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399995000 Hz
2021-09-05 14:46:14.944724: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3d6f490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-05 14:46:14.944972: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-09-05 14:46:14,945 root  INFO     Building a dataset from ./Busy/admin/test/01/labels/training_labels.txt.
2021-09-05 14:46:14,947 root  INFO     Output file: ./Busy/admin/test/01/labels/training.tfrecords
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

2021-09-05 14:46:19.870348: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-05 14:46:19.877103: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399995000 Hz
2021-09-05 14:46:19.877646: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5252d10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-05 14:46:19.877725: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-09-05 14:46:19,878 root  INFO     Building a dataset from ./Busy/admin/test/01/labels/testing_labels.txt.
2021-09-05 14:46:19,880 root  INFO     Output file: ./Busy/admin/test/01/labels/testing.tfrecords
INFO:Captcha22 Engine:Create model
INFO:Captcha22 Engine:./Unsorted/admin_test_01.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 35, in __init__
    f = open(self.path + 'model.txt')
FileNotFoundError: [Errno 2] No such file or directory: './Busy/admin/test/01/model.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/captcha22/__main__.py", line 278, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/core/server.py", line 22, in server
    server.main()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 519, in main
    self.run_server()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 494, in run_server
    self.check_files()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 409, in check_files
    self.create_model(file)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 375, in create_model
    model = captcha(path, self.logger)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 55, in __init__
    self.get_image_size()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 61, in get_image_size
    img = cv2.imread(images[0])
IndexError: list index out of range

**Comment by vneroica** [comment]
another part of error log message:

INFO:Captcha22 Engine:Create labels
INFO:Captcha22 Engine:Directories is:
INFO:Captcha22 Engine:./Busy/admin/data/02/data/
INFO:Captcha22 Engine:./Busy/admin/data/02/labels/
INFO:Captcha22 Engine:Generate aocr
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

2021-09-05 15:19:42.198109: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-05 15:19:42.225482: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399995000 Hz
2021-09-05 15:19:42.226438: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4161a30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-05 15:19:42.226548: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-09-05 15:19:42,230 root  INFO     Building a dataset from ./Busy/admin/data/02/labels/training_labels.txt.
2021-09-05 15:19:42,231 root  INFO     Output file: ./Busy/admin/data/02/labels/training.tfrecords
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/aocr/__main__.py:20: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

2021-09-05 15:19:47.271215: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-05 15:19:47.281283: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399995000 Hz
2021-09-05 15:19:47.281873: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x43e5060 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-05 15:19:47.281935: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-09-05 15:19:47,283 root  INFO     Building a dataset from ./Busy/admin/data/02/labels/testing_labels.txt.
2021-09-05 15:19:47,285 root  INFO     Output file: ./Busy/admin/data/02/labels/testing.tfrecords
INFO:Captcha22 Engine:Create model
INFO:Captcha22 Engine:./Unsorted/admin_data_02.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 35, in __init__
    f = open(self.path + 'model.txt')
FileNotFoundError: [Errno 2] No such file or directory: './Busy/admin/data/02/model.txt'

**Comment by TinusGreen** [comment]
Hi vneroica,

From what I can determine there is something wrong with your training. 

Can you perhaps provide me with:

1. Details on how you uploaded your ZIP file for training
2. The generated a file called aocr.log

This will help me debug the issue at hand.

**Comment by vneroica** [comment]
> Hi vneroica,
> 
> From what I can determine there is something wrong with your training.
> 
> Can you perhaps provide me with:
> 
> 1. Details on how you uploaded your ZIP file for training
> 2. The generated a file called aocr.log
> 
> This will help me debug the issue at hand.
Thank you for your reply, TinusGreen.
 
These are the details you need: 

1. I created and copied the ZIP file to Unsorted folder.

2. aocr.log file:
2021-09-05 15:19:42,230 root  INFO     Building a dataset from ./Busy/admin/data
/02/labels/training_labels.txt.
2021-09-05 15:19:42,231 root  INFO     Output file: ./Busy/admin/data/02/labels/
training.tfrecords
2021-09-05 15:19:47,283 root  INFO     Building a dataset from ./Busy/admin/data
/02/labels/testing_labels.txt.
2021-09-05 15:19:47,285 root  INFO     Output file: ./Busy/admin/data/02/labels/
testing.tfrecords

**Comment by TinusGreen** [comment]
Hi vneroica,

If that's all that is in your aocr log file then training never occurred even though the system says it got finalised.

Could you perhaps do the following and provide me with the aocr log file again:

1. Delete your Busy, Model, and Unsorted folders.
2. Rerun the program and dump the zip file into unsorted again.

Also, once done, can you please provide me with a listing of the ./Busy/admin/data/01/ directory?

**Comment by vneroica** [comment]
Hi TinusGreen,

Sorry for my late reply.
I deteled Busy, Model and Unsorted folders and Rerun program, this is an error log when rerun program (copied admin_data_02.zip file to unsorted folder):

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 35, in __init__
    f = open(self.path + 'model.txt')
FileNotFoundError: [Errno 2] No such file or directory: './Busy/admin/data/02/model.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/captcha22/__main__.py", line 278, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/core/server.py", line 22, in server
    server.main()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 519, in main
    self.run_server()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 494, in run_server
    self.check_files()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 409, in check_files
    self.create_model(file)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 375, in create_model
    model = captcha(path, self.logger)
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 55, in __init__
    self.get_image_size()
  File "/usr/local/lib/python3.6/dist-packages/captcha22/lib/server/captcha22.py", line 61, in get_image_size
    img = cv2.imread(images[0])
IndexError: list index out of range
/// log ended

listing of the ./Busy/admin/data/02 folder:

~/workspace# ls Busy/admin/data/02/
README.txt          labels_level_2.csv  labels_level_5.csv  level_3
labels              labels_level_3.csv  level_1             level_4
labels_level_1.csv  labels_level_4.csv  level_2             level_5

and this is aocr.log's content:

 cat aocr.log
2021-09-09 17:42:02,180 root  INFO     Building a dataset from ./Busy/admin/data/02/labels/training_labels.txt.
2021-09-09 17:42:02,182 root  INFO     Output file: ./Busy/admin/data/02/labels/training.tfrecords
2021-09-09 17:42:07,448 root  INFO     Building a dataset from ./Busy/admin/data/02/labels/testing_labels.txt.
2021-09-09 17:42:07,449 root  INFO     Output file: ./Busy/admin/data/02/labels/testing.tfrecords

**Comment by TinusGreen** [comment]
Hi vneroica,

Apologies for the delay.

Based on your folder listing, I'm pretty sure your ZIP is not correct. Which is what is causing the issue. Your zip should look something like this:

```
ZIP:
data/
data/HJFGD.png
data/JFHDS.png
data/KLJFD.png
```

So in essence, the zip should contain a folder called `data` with your labelled imaged within. If you used the labelling scripts, it should have created such a zip for you, otherwise you can create it yourself as well.

Please flush the folders again and retry with a correct zip and let me know what happens.

**Comment by vneroica** [comment]
> Hi vneroica,
> 
> Apologies for the delay.
> 
> Based on your folder listing, I'm pretty sure your ZIP is not correct. Which is what is causing the issue. Your zip should look something like this:
> 
> ```
> ZIP:
> data/
> data/HJFGD.png
> data/JFHDS.png
> data/KLJFD.png
> ```
> 
> So in essence, the zip should contain a folder called `data` with your labelled imaged within. If you used the labelling scripts, it should have created such a zip for you, otherwise you can create it yourself as well.
> 
> Please flush the folders again and retry with a correct zip and let me know what happens.

Hi TinusGreen,

Thanks so much for your help. I changed content to the format you suggested and model is trained successfully. I think you should update "how to create zip file manually" to readme.

Now i test the model with curl as the guide in readme:

curl -X POST \
    http://localhost:9001/v1/models/<yourmodelname>:predict \
    -H 'cache-control: no-cache' \
    -H 'content-type: application/json' \
    -d '{
            "signature_name": "serving_default",
            "inputs": 
            {
                "input": { "b64": "/9j/4AAQ==" }
            }
        }'

The output of that curl command is:
{
    "outputs": {
        "probability": 0.029679877185022473,
        "output": "FFFF"
    }
}

that is not a correct result of my captcha. i repeat a lot of time but the same result, "output": "FFFF".  Please tell me what is wrong here?

**Comment by TinusGreen** [comment]
Hi vneroica,

We had that in that past, however if you use the full tool, such as `captcha22 client label` for your labelling, it should create the zip with the correct folder structure automatically.

In the same line, the captcha22 API should be able to help you display information regarding the training of your captchas. So if you had the following two running:

```
captcha22 server engine
captcha22 server api
```

You should be able to interface with the captcha server using `captcha22 client api`.

The entire model is built around having a central (powerful) server where you crack captchas and then using the client to interface with the API. The API options would allow you to see processed training results, which will allow you to see the accuracy that your model achieved.

 You can of course also do this manually and just go read the aocr.log file in that specific model's directory, which will show you the accuracy results of the test. 

If your model has not been trained adequately, you will not get good results for your captcha solutions. You will then have to add more captchas to your training samples to make it more accurate.

However, please also just make sure that you are giving the correct input for the CURL command:

`"input": { "b64": "/9j/4AAQ==" }` - Is where you should be inserting your captcha in base64 format for the system to crack. If the format here is wrong, it would also default to "FFFF".

Hope this helps.

**Comment by vneroica** [comment]
> Hi vneroica,
> 
> We had that in that past, however if you use the full tool, such as `captcha22 client label` for your labelling, it should create the zip with the correct folder structure automatically.
> 
> In the same line, the captcha22 API should be able to help you display information regarding the training of your captchas. So if you had the following two running:
> 
> ```
> captcha22 server engine
> captcha22 server api
> ```
> 
> You should be able to interface with the captcha server using `captcha22 client api`.
> 
> The entire model is built around having a central (powerful) server where you crack captchas and then using the client to interface with the API. The API options would allow you to see processed training results, which will allow you to see the accuracy that your model achieved.
> 
> You can of course also do this manually and just go read the aocr.log file in that specific model's directory, which will show you the accuracy results of the test.
> 
> If your model has not been trained adequately, you will not get good results for your captcha solutions. You will then have to add more captchas to your training samples to make it more accurate.
> 
> However, please also just make sure that you are giving the correct input for the CURL command:
> 
> `"input": { "b64": "/9j/4AAQ==" }` - Is where you should be inserting your captcha in base64 format for the system to crack. If the format here is wrong, it would also default to "FFFF".
> 
> Hope this helps.

Dear TinusGreen,

i understand that i can create ZIP file via client API but client API required GUI library Tkinter, and almost linux server not support GUI, that is why i must create ZIP file manually.

I inserted an exact base64 format to input to test model but the output still be "FFFF", can you check that for me?

**Comment by TinusGreen** [comment]
Hi vneroica,

I can't really check anything on my side? The trained model is on your side. Like mentioned before, you need to review the model's accuracy. If not through the API, then manually through inspection of the `aocr.log` file.

Should the accuracy be sufficient, then you need to debug your base64 encoded image, making sure that it is exactly in the same format as the data sent for training.

Without visibility of your training log or the model, I can't be of more assistance.

**Comment by TinusGreen** [comment]
Closing due to non-issue on Captcha22. Will still provide support on closed ticket.
