### ISSUE TITLE
Unable to run captcha22 server engine on Macos 

### ISSUE THREAD

**Issue by vu159951** [FSecureLABS/captcha22#2]
I'm on mac 10.15.1 (19B2106) with Anaconda installed (tensorflow, python 3.6 installed).
Beginning of the error:

``
Class start
Checking if there is any new files
['./Unsorted/admin_2_2.zip']
Start running
Copy files
Starting the copy of files
mkdir: ./Busy/: File exists
Traceback (most recent call last):
  File "/Users/abc/opt/anaconda3/envs/captcha/bin/captcha22", line 8, in <module>
    sys.exit(main())
  File "/Users/abc/opt/anaconda3/envs/captcha/lib/python3.6/site-packages/captcha22/__main__.py", line 267, in main
    args.func(args)
  File "/Users/abc/opt/anaconda3/envs/captcha/lib/python3.6/site-packages/captcha22/lib/core/server.py", line 20, in server
    server.main()
  File "/Users/abc/opt/anaconda3/envs/captcha/lib/python3.6/site-packages/captcha22/lib/server/captcha22.py", line 503, in main
    self.run_server()
  File "/Users/abc/opt/anaconda3/envs/captcha/lib/python3.6/site-packages/captcha22/lib/server/captcha22.py", line 478, in run_server
    self.check_files()
  File "/Users/abc/opt/anaconda3/envs/captcha/lib/python3.6/site-packages/captcha22/lib/server/captcha22.py", line 387, in check_files
    self.copy_files(file)
  File "/Users/abc/opt/anaconda3/envs/captcha/lib/python3.6/site-packages/captcha22/lib/server/captcha22.py", line 253, in copy_files
    os.system('mkdir ' + self.busy_URL + "/" + names[0] + "/" + names[1])
IndexError: list index out of range
``

**Comment by TinusGreen** [comment]
Hi vu159951,

The issue seems to be the default directories. The extraction of the details fails.

I found the issue and have applied a patch but I want to make sure that it is working before I commit it to the repo.

While I test the patch, you can fix the issue by using the following arguments from the directory where you want to run the engine:

`captcha22 server engine --input-folder=Unsorted --work-folder=Busy --model-folder=Models`

**Comment by TinusGreen** [comment]
The following commit should have solved the issue:

https://github.com/FSecureLABS/captcha22/commit/ff5b74df9633bf5af38b962425097e9455c2c648

I've tested the patch on both of our rigs and it is working. Can you please update your captcha22 pip package, test again and let me know if this fixes the issue for you?

**Comment by vu159951** [comment]
Hi TinusGreen,

I applied the patch and the old issue gone.

 Thank you.

**Comment by TinusGreen** [comment]
Thanks for letting me know!
