### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by fastchain** [FSecureLABS/captcha22#23]
Hello,

on 
```
captcha22 server engine
```

I get this

```
INFO:Captcha22 Engine:Create labels
INFO:Captcha22 Engine:Directories is:
INFO:Captcha22 Engine:./Busy/admin/2/1/data/
INFO:Captcha22 Engine:./Busy/admin/2/1/labels/
INFO:Captcha22 Engine:Generate aocr
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aocr/model/seq2seq.py", line 73, in <module>
    linear = rnn_cell_impl._linear  # pylint: disable=protected-access
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 5, in <module>
    from aocr.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/aocr/__main__.py", line 14, in <module>
    from .model.model import Model
  File "/usr/local/lib/python3.6/dist-packages/aocr/model/model.py", line 18, in <module>
    from .seq2seq_model import Seq2SeqModel
  File "/usr/local/lib/python3.6/dist-packages/aocr/model/seq2seq_model.py", line 25, in <module>
    from .seq2seq import model_with_buckets
  File "/usr/local/lib/python3.6/dist-packages/aocr/model/seq2seq.py", line 76, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
ModuleNotFoundError: No module named 'tensorflow.contrib'

```

```
jet@jet:~/captcher$ uname -a
Linux jet 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
```

```
jet@jet:~/captcher$ python --version
Python 3.6.9
jet@jet:~/captcher$ pip --version
pip 21.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
jet@jet:~/captcher$
```

```
jet@jet:~/captcher$ python 
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> import tensorflow as tf; print(tf.__version__)
2.6.2
```

What am I doin wrong?

Thank you

**Comment by fastchain** [comment]
Not compatible with tensorflow2

**Comment by TinusGreen** [comment]
Hi fastchain,

Apologies for the late response. I was away without access to my PC.

Yes, AOCR, which is the main ocr lib used by captcha22 is currently only supported in TF<2. We are looking to move away from AOCR and embed our own OCR engine, but that will still take quite a bit of time.
