### ISSUE TITLE
Error Running Captcha22 In Terminal after installing on UBUNTU 20.04.1 LTS

### ISSUE THREAD

**Issue by graham-eisele** [FSecureLABS/captcha22#5]
Installing captcha22 using both pip install captcha22 and install from the source seem to work fine, but when running right after installing, I get this error:

`user@user-Predator-G3-571:~$ captcha22
Traceback (most recent call last):
  File "/usr/local/bin/captcha22", line 11, in <module>
    load_entry_point('captcha22==1.0.1', 'console_scripts', 'captcha22')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.local/lib/python3.8/site-packages/captcha22/__main__.py", line 12, in <module>
    from lib.core.client import (api_basic, api_full, captcha_labeller,
ModuleNotFoundError: No module named 'lib.core'
user@user-Predator-G3-571:~$ 
`

**Comment by TinusGreen** [comment]
Hi there,

I tried to replicate your error but was unable to. I was using a clean Ubuntu 20.04 image, installing Python3.8 and pip before installing captcha22 and I'm able to get the prompt. 

The issue seems to be that it can not load the specified modules of captcha22.

Are you running this in a virtual environment? As indicated by  #3, captcha22 does not currently support virtual environments.

**Comment by graham-eisele** [comment]
No, It is running natively.

**Comment by TinusGreen** [comment]
I've found the issue in the import. Initial tests show that it has been resolved. I'll upload a new pip package version and update the repo.
